---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Accueil
- type: directory
  path: musicians
  label: Musiciens
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: document
  path: videos/**/*
  label: Vidéos
- type: document
  path: tour/**/*
  label: Tour
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
