---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/home
  label: Accueil
  create: all
  match: "**/*"
  templates:
  - home
- type: directory
  path: content/musicians
  label: Musiciens
  create: all
  match: "**/*"
  templates:
  - musician
- type: directory
  path: content/videos
  label: Vidéos
  create: all
  match: "**/*"
  templates:
  - videos
- type: directory
  path: content/tour
  label: Tour
  create: all
  match: "**/*"
  templates:
  - tour
- type: directory
  path: content/contact
  label: Contact
  create: all
  match: "**/*"
  templates:
  - contact
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: npm run forestry-preview
